// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemon.Infra.Data.Context;

#nullable disable

namespace Pokemon.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230918170956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Pokemon.Domain.Entities.PokemonCaptured", b =>
                {
                    b.Property<string>("pokemon_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("pokemon_name");

                    b.Property<string>("master_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("master_name");

                    b.Property<int?>("PokemonMasterid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("capture_date")
                        .HasColumnType("datetime")
                        .HasColumnName("capture_date");

                    b.HasKey("pokemon_name", "master_name")
                        .HasName("PK__pokemon_captured");

                    b.HasIndex("PokemonMasterid");

                    b.ToTable("pokemon_captured", (string)null);
                });

            modelBuilder.Entity("Pokemon.Domain.Entities.PokemonMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("age")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("cpf")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("id")
                        .HasName("PK__pokemon_master");

                    b.ToTable("pokemon_master", (string)null);
                });

            modelBuilder.Entity("Pokemon.Domain.Entities.PokemonCaptured", b =>
                {
                    b.HasOne("Pokemon.Domain.Entities.PokemonMaster", null)
                        .WithMany("captuerd_pokemons")
                        .HasForeignKey("PokemonMasterid");
                });

            modelBuilder.Entity("Pokemon.Domain.Entities.PokemonMaster", b =>
                {
                    b.Navigation("captuerd_pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
